// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhX1RpSDmIIt4_V-YQXaPUiP0Khl9lV-Q',
    appId: '1:1015109170982:web:8330cf25298326b6c073e7',
    messagingSenderId: '1015109170982',
    projectId: 'shrouk2-21ee8',
    authDomain: 'shrouk2-21ee8.firebaseapp.com',
    storageBucket: 'shrouk2-21ee8.firebasestorage.app',
    measurementId: 'G-VPV4PPL6F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDunItjFvUukwnZA49ENbmtBleEwYrXbkg',
    appId: '1:1015109170982:android:784ccc22133888c9c073e7',
    messagingSenderId: '1015109170982',
    projectId: 'shrouk2-21ee8',
    storageBucket: 'shrouk2-21ee8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDN16H9tqoteynrn1W5DJV5uXMAWpBnXk',
    appId: '1:1015109170982:ios:596a4136d956f4e6c073e7',
    messagingSenderId: '1015109170982',
    projectId: 'shrouk2-21ee8',
    storageBucket: 'shrouk2-21ee8.firebasestorage.app',
    iosBundleId: 'com.example.itiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDN16H9tqoteynrn1W5DJV5uXMAWpBnXk',
    appId: '1:1015109170982:ios:596a4136d956f4e6c073e7',
    messagingSenderId: '1015109170982',
    projectId: 'shrouk2-21ee8',
    storageBucket: 'shrouk2-21ee8.firebasestorage.app',
    iosBundleId: 'com.example.itiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhX1RpSDmIIt4_V-YQXaPUiP0Khl9lV-Q',
    appId: '1:1015109170982:web:cee995b01b93f1d0c073e7',
    messagingSenderId: '1015109170982',
    projectId: 'shrouk2-21ee8',
    authDomain: 'shrouk2-21ee8.firebaseapp.com',
    storageBucket: 'shrouk2-21ee8.firebasestorage.app',
    measurementId: 'G-1WWEKVT1NJ',
  );
}
